//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGHISJKZGQ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:4319/WebSite1/Service.asmx")]
        public string PATHGETHISZGQ_webserverAAA_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_webserverAAA_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.68:58080/csp/tongji/Tongji.COMM.SoapService.PathologySysService" +
            ".cls")]
        public string PATHGETHISZGQ_WebTJ_PathologySysService {
            get {
                return ((string)(this["PATHGETHISZGQ_WebTJ_PathologySysService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.48.45.107/ktpis/PisServiceLJ.asmx")]
        public string PATHGETHISZGQ_WebReference_PisServiceLJ {
            get {
                return ((string)(this["PATHGETHISZGQ_WebReference_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.100.53:8080/Service.asmx")]
        public string PATHGETHISZGQ_szyyWEB_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_szyyWEB_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.100.64:8082/PisServiceLJ.asmx")]
        public string PATHGETHISZGQ_nbyzrmyyWeb_PisServiceLJ {
            get {
                return ((string)(this["PATHGETHISZGQ_nbyzrmyyWeb_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.60.39:57772/csp/i-risservice/DHC.RIS.BS.WebRisService.cls")]
        public string PATHGETHISZGQ_whxhyyWEB_WebRisService {
            get {
                return ((string)(this["PATHGETHISZGQ_whxhyyWEB_WebRisService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.201.4/dthealth/web//web.ToBLCom.cls")]
        public string PATHGETHISZGQ_ahzlyyWeb_XDInterface {
            get {
                return ((string)(this["PATHGETHISZGQ_ahzlyyWeb_XDInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.52.100:8081/PisServiceLJ.asmx")]
        public string PATHGETHISZGQ_nbyz2yWEB_PisServiceLJ {
            get {
                return ((string)(this["PATHGETHISZGQ_nbyz2yWEB_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.15:8080/Services/NYwclService")]
        public string PATHGETHISZGQ_cszxyyWEB_NYwclService {
            get {
                return ((string)(this["PATHGETHISZGQ_cszxyyWEB_NYwclService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://111.111.116.8:8071/LJservice.asmx")]
        public string PATHGETHISZGQ_sxzlyyWeb_Service1 {
            get {
                return ((string)(this["PATHGETHISZGQ_sxzlyyWeb_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://132.147.254.44:57772/csp/supcon/WebApp.WSGeneral.cls")]
        public string PATHGETHISZGQ_WebXYCX_WSGeneral {
            get {
                return ((string)(this["PATHGETHISZGQ_WebXYCX_WSGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.8.100/TrasenWS.asmx")]
        public string PATHGETHISZGQ_hnsrmyyWeb_TrasenWS {
            get {
                return ((string)(this["PATHGETHISZGQ_hnsrmyyWeb_TrasenWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://168.192.8.10:8080/WebService/services/MatrixService")]
        public string PATHGETHISZGQ_SXDEYWeb_MatrixService {
            get {
                return ((string)(this["PATHGETHISZGQ_SXDEYWeb_MatrixService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.95.141:8003/Service.asmx")]
        public string PATHGETHISZGQ_ZSZLWeb_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_ZSZLWeb_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.1.71:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PATHGETHISZGQ_fjsfywebwerice1_WSInterface {
            get {
                return ((string)(this["PATHGETHISZGQ_fjsfywebwerice1_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.1.71:1508/services/WSInterface_cdr.WSInterface_cdrHttpSoap11Endpoint")]
        public string PATHGETHISZGQ_fjsfyWeb_WSInterface_cdr {
            get {
                return ((string)(this["PATHGETHISZGQ_fjsfyWeb_WSInterface_cdr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://198.100.100.8:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PATHGETHISZGQ_fjsfybjyWeb_WSInterface {
            get {
                return ((string)(this["PATHGETHISZGQ_fjsfybjyWeb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.158:1405/services/FGPLService.FGPLServiceHttpSoap12Endpoint")]
        public string PATHGETHISZGQ_shsjdzyyyweb_FGPLService {
            get {
                return ((string)(this["PATHGETHISZGQ_shsjdzyyyweb_FGPLService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.158:1401/services/FGPublicService.FGPublicServiceHttpSoap12Endpo" +
            "int")]
        public string PATHGETHISZGQ_shsjdqzyyyweb2_FGPublicService {
            get {
                return ((string)(this["PATHGETHISZGQ_shsjdqzyyyweb2_FGPublicService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dfg:29000/services/WinningHIIPService.WinningHIIPServiceHttpSoap11Endpoint" +
            "")]
        public string PATHGETHISZGQ_xjshz_winning_web_WinningHIIPService {
            get {
                return ((string)(this["PATHGETHISZGQ_xjshz_winning_web_WinningHIIPService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.1.71/webapp/pathologyservice.asmx")]
        public string PATHGETHISZGQ_jssfyweb_PathologyService {
            get {
                return ((string)(this["PATHGETHISZGQ_jssfyweb_PathologyService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        public string PATHGETHISZGQ_sh7yweb_webserviceService {
            get {
                return ((string)(this["PATHGETHISZGQ_sh7yweb_webserviceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://155.165.13.14:8085/sevenHospitalService/services/healthService.healthServi" +
            "ceHttpSoap11Endpoint/")]
        public string PATHGETHISZGQ_sh7yweb2_healthService {
            get {
                return ((string)(this["PATHGETHISZGQ_sh7yweb2_healthService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.51:57772/csp/dhcens/DHC.Pis.XiangYaOne.BS.Web.cls")]
        public string PATHGETHISZGQ_xyfyyyweb1_DHC_Pis_XiangYaOne {
            get {
                return ((string)(this["PATHGETHISZGQ_xyfyyyweb1_DHC_Pis_XiangYaOne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.10.33.84/zsyyWebService/Service.asmx")]
        public string PATHGETHISZGQ_xmzsyyWeb_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_xmzsyyWeb_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://223.220.200.45:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PATHGETHISZGQ_aydefyweb_WSInterface {
            get {
                return ((string)(this["PATHGETHISZGQ_aydefyweb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://100.100.42.107/GetEHMQ/EHSBMQService.asmx")]
        public string PATHGETHISZGQ_EHSBMQWeb_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_EHSBMQWeb_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.0.19.148:1506/services/WSInterface.WSInterfaceHttpSoap11Endpoint")]
        public string PATHGETHISZGQ_xm1yweb_WSInterface {
            get {
                return ((string)(this["PATHGETHISZGQ_xm1yweb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.101.175:1006/services/PlatformCommonSvr.PlatformCommonSvrHttpSoap1" +
            "1Endpoint")]
        public string PATHGETHISZGQ_zjgsdyrmyyweb_PlatformCommonSvr {
            get {
                return ((string)(this["PATHGETHISZGQ_zjgsdyrmyyweb_PlatformCommonSvr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1266/ZSZL_MQService2010/MQService.asmx")]
        public string PATHGETHISZGQ_ZSZLWeb_ZGQ_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_ZSZLWeb_ZGQ_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.95.230/BLService/Service.asmx")]
        public string PATHGETHISZGQ_ZszlHISWEB_ZGQ_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_ZszlHISWEB_ZGQ_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.9.199.12:8002/HisForInspectItemService.asmx")]
        public string PATHGETHISZGQ_gdszyyMzHisWeb_HisForInspectItemService {
            get {
                return ((string)(this["PATHGETHISZGQ_gdszyyMzHisWeb_HisForInspectItemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.200.119:57772/csp/xyepacs/PACS.BS.Service.cls")]
        public string PATHGETHISZGQ_xy2yWebService_XYEPACS {
            get {
                return ((string)(this["PATHGETHISZGQ_xy2yWebService_XYEPACS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svc.chas.gdhtcm.com:9080/ChasSvc/services/ChasCommonPort")]
        public string PATHGETHISZGQ_gdszyyWS_ChasCommonSvc {
            get {
                return ((string)(this["PATHGETHISZGQ_gdszyyWS_ChasCommonSvc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.9.202.71:8181/IBMLisHisWebservice/LisService.asmx")]
        public string PATHGETHISZGQ_gdszyytjWeb_LisService {
            get {
                return ((string)(this["PATHGETHISZGQ_gdszyytjWeb_LisService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.168.35.249/BLToMQWebSrv/FZMQService.asmx")]
        public string PATHGETHISZGQ_BLToFZMQWS_Service {
            get {
                return ((string)(this["PATHGETHISZGQ_BLToFZMQWS_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.95.189:8081/PDAService.asmx")]
        public string PATHGETHISZGQ_GzzszlfzLis_PDAService {
            get {
                return ((string)(this["PATHGETHISZGQ_GzzszlfzLis_PDAService"]));
            }
        }
    }
}
