//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace PathHISZGQJK.lzfbws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FuJianJieKouForBCaoSoap", Namespace="http://www.hongyangsoft.com/")]
    public partial class FuJianJieKouForBCao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BLiShenQingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadBingRenDangAnOperationCompleted;
        
        private System.Threading.SendOrPostCallback BLiBaoGaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback JianChaQueRenOperationCompleted;
        
        private System.Threading.SendOrPostCallback FuJianJianChaAndGenXinFeiYongOperationCompleted;
        
        private System.Threading.SendOrPostCallback FuJianQuXiaoJianChaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FuJianJieKouForBCao() {
            this.Url = global::PathHISZGQJK.Properties.Settings.Default.PathHISZGQJK_lzfbws_FuJianJieKouForBCao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BLiShenQingCompletedEventHandler BLiShenQingCompleted;
        
        /// <remarks/>
        public event ReadBingRenDangAnCompletedEventHandler ReadBingRenDangAnCompleted;
        
        /// <remarks/>
        public event BLiBaoGaoCompletedEventHandler BLiBaoGaoCompleted;
        
        /// <remarks/>
        public event JianChaQueRenCompletedEventHandler JianChaQueRenCompleted;
        
        /// <remarks/>
        public event FuJianJianChaAndGenXinFeiYongCompletedEventHandler FuJianJianChaAndGenXinFeiYongCompleted;
        
        /// <remarks/>
        public event FuJianQuXiaoJianChaCompletedEventHandler FuJianQuXiaoJianChaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/BLiShenQing", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BLiShenQing(string huakuaxinxi, string laiYuan) {
            object[] results = this.Invoke("BLiShenQing", new object[] {
                        huakuaxinxi,
                        laiYuan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BLiShenQingAsync(string huakuaxinxi, string laiYuan) {
            this.BLiShenQingAsync(huakuaxinxi, laiYuan, null);
        }
        
        /// <remarks/>
        public void BLiShenQingAsync(string huakuaxinxi, string laiYuan, object userState) {
            if ((this.BLiShenQingOperationCompleted == null)) {
                this.BLiShenQingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBLiShenQingOperationCompleted);
            }
            this.InvokeAsync("BLiShenQing", new object[] {
                        huakuaxinxi,
                        laiYuan}, this.BLiShenQingOperationCompleted, userState);
        }
        
        private void OnBLiShenQingOperationCompleted(object arg) {
            if ((this.BLiShenQingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BLiShenQingCompleted(this, new BLiShenQingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/ReadBingRenDangAn", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadBingRenDangAn(string huakuaxinxi, string laiYuan) {
            object[] results = this.Invoke("ReadBingRenDangAn", new object[] {
                        huakuaxinxi,
                        laiYuan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadBingRenDangAnAsync(string huakuaxinxi, string laiYuan) {
            this.ReadBingRenDangAnAsync(huakuaxinxi, laiYuan, null);
        }
        
        /// <remarks/>
        public void ReadBingRenDangAnAsync(string huakuaxinxi, string laiYuan, object userState) {
            if ((this.ReadBingRenDangAnOperationCompleted == null)) {
                this.ReadBingRenDangAnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadBingRenDangAnOperationCompleted);
            }
            this.InvokeAsync("ReadBingRenDangAn", new object[] {
                        huakuaxinxi,
                        laiYuan}, this.ReadBingRenDangAnOperationCompleted, userState);
        }
        
        private void OnReadBingRenDangAnOperationCompleted(object arg) {
            if ((this.ReadBingRenDangAnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadBingRenDangAnCompleted(this, new ReadBingRenDangAnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/BLiBaoGao", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BLiBaoGao(string xmlBaoGao) {
            object[] results = this.Invoke("BLiBaoGao", new object[] {
                        xmlBaoGao});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BLiBaoGaoAsync(string xmlBaoGao) {
            this.BLiBaoGaoAsync(xmlBaoGao, null);
        }
        
        /// <remarks/>
        public void BLiBaoGaoAsync(string xmlBaoGao, object userState) {
            if ((this.BLiBaoGaoOperationCompleted == null)) {
                this.BLiBaoGaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBLiBaoGaoOperationCompleted);
            }
            this.InvokeAsync("BLiBaoGao", new object[] {
                        xmlBaoGao}, this.BLiBaoGaoOperationCompleted, userState);
        }
        
        private void OnBLiBaoGaoOperationCompleted(object arg) {
            if ((this.BLiBaoGaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BLiBaoGaoCompleted(this, new BLiBaoGaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/JianChaQueRen", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JianChaQueRen(string fuJianID, string keShiID, string yongHuID, string yongHuMing, string leiXing) {
            object[] results = this.Invoke("JianChaQueRen", new object[] {
                        fuJianID,
                        keShiID,
                        yongHuID,
                        yongHuMing,
                        leiXing});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JianChaQueRenAsync(string fuJianID, string keShiID, string yongHuID, string yongHuMing, string leiXing) {
            this.JianChaQueRenAsync(fuJianID, keShiID, yongHuID, yongHuMing, leiXing, null);
        }
        
        /// <remarks/>
        public void JianChaQueRenAsync(string fuJianID, string keShiID, string yongHuID, string yongHuMing, string leiXing, object userState) {
            if ((this.JianChaQueRenOperationCompleted == null)) {
                this.JianChaQueRenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJianChaQueRenOperationCompleted);
            }
            this.InvokeAsync("JianChaQueRen", new object[] {
                        fuJianID,
                        keShiID,
                        yongHuID,
                        yongHuMing,
                        leiXing}, this.JianChaQueRenOperationCompleted, userState);
        }
        
        private void OnJianChaQueRenOperationCompleted(object arg) {
            if ((this.JianChaQueRenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JianChaQueRenCompleted(this, new JianChaQueRenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/FuJianJianChaAndGenXinFeiYong", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FuJianJianChaAndGenXinFeiYong(string fujianid, string zhixingkeshi, string zhixingyonghuid, string zhixingyonghuming, string laiyuan) {
            object[] results = this.Invoke("FuJianJianChaAndGenXinFeiYong", new object[] {
                        fujianid,
                        zhixingkeshi,
                        zhixingyonghuid,
                        zhixingyonghuming,
                        laiyuan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FuJianJianChaAndGenXinFeiYongAsync(string fujianid, string zhixingkeshi, string zhixingyonghuid, string zhixingyonghuming, string laiyuan) {
            this.FuJianJianChaAndGenXinFeiYongAsync(fujianid, zhixingkeshi, zhixingyonghuid, zhixingyonghuming, laiyuan, null);
        }
        
        /// <remarks/>
        public void FuJianJianChaAndGenXinFeiYongAsync(string fujianid, string zhixingkeshi, string zhixingyonghuid, string zhixingyonghuming, string laiyuan, object userState) {
            if ((this.FuJianJianChaAndGenXinFeiYongOperationCompleted == null)) {
                this.FuJianJianChaAndGenXinFeiYongOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFuJianJianChaAndGenXinFeiYongOperationCompleted);
            }
            this.InvokeAsync("FuJianJianChaAndGenXinFeiYong", new object[] {
                        fujianid,
                        zhixingkeshi,
                        zhixingyonghuid,
                        zhixingyonghuming,
                        laiyuan}, this.FuJianJianChaAndGenXinFeiYongOperationCompleted, userState);
        }
        
        private void OnFuJianJianChaAndGenXinFeiYongOperationCompleted(object arg) {
            if ((this.FuJianJianChaAndGenXinFeiYongCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FuJianJianChaAndGenXinFeiYongCompleted(this, new FuJianJianChaAndGenXinFeiYongCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.hongyangsoft.com/FuJianQuXiaoJianCha", RequestNamespace="http://www.hongyangsoft.com/", ResponseNamespace="http://www.hongyangsoft.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FuJianQuXiaoJianCha(string fujianid, string laiyuan) {
            object[] results = this.Invoke("FuJianQuXiaoJianCha", new object[] {
                        fujianid,
                        laiyuan});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FuJianQuXiaoJianChaAsync(string fujianid, string laiyuan) {
            this.FuJianQuXiaoJianChaAsync(fujianid, laiyuan, null);
        }
        
        /// <remarks/>
        public void FuJianQuXiaoJianChaAsync(string fujianid, string laiyuan, object userState) {
            if ((this.FuJianQuXiaoJianChaOperationCompleted == null)) {
                this.FuJianQuXiaoJianChaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFuJianQuXiaoJianChaOperationCompleted);
            }
            this.InvokeAsync("FuJianQuXiaoJianCha", new object[] {
                        fujianid,
                        laiyuan}, this.FuJianQuXiaoJianChaOperationCompleted, userState);
        }
        
        private void OnFuJianQuXiaoJianChaOperationCompleted(object arg) {
            if ((this.FuJianQuXiaoJianChaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FuJianQuXiaoJianChaCompleted(this, new FuJianQuXiaoJianChaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BLiShenQingCompletedEventHandler(object sender, BLiShenQingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BLiShenQingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BLiShenQingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadBingRenDangAnCompletedEventHandler(object sender, ReadBingRenDangAnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadBingRenDangAnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadBingRenDangAnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BLiBaoGaoCompletedEventHandler(object sender, BLiBaoGaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BLiBaoGaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BLiBaoGaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void JianChaQueRenCompletedEventHandler(object sender, JianChaQueRenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JianChaQueRenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JianChaQueRenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FuJianJianChaAndGenXinFeiYongCompletedEventHandler(object sender, FuJianJianChaAndGenXinFeiYongCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuJianJianChaAndGenXinFeiYongCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FuJianJianChaAndGenXinFeiYongCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FuJianQuXiaoJianChaCompletedEventHandler(object sender, FuJianQuXiaoJianChaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuJianQuXiaoJianChaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FuJianQuXiaoJianChaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591