//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.42 版自动生成。
// 
#pragma warning disable 1591

namespace PATHGETHISZGQ.whxhyyWEB {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebRisServiceSoap", Namespace="http://tempuri.org")]
    public partial class WebRisService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAppFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBookedInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCancelBookedInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCancelFeeAppOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCancelReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCheckCompleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDictInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatInfoToRISOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPatOrdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReturnReportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPatOrdListToRisOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebRisService() {
            this.Url = global::PATHGETHISZGQ.Properties.Settings.Default.PATHGETHISZGQ_whxhyyWEB_WebRisService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAppFormCompletedEventHandler GetAppFormCompleted;
        
        /// <remarks/>
        public event GetBookedInfoCompletedEventHandler GetBookedInfoCompleted;
        
        /// <remarks/>
        public event GetCancelBookedInfoCompletedEventHandler GetCancelBookedInfoCompleted;
        
        /// <remarks/>
        public event GetCancelFeeAppCompletedEventHandler GetCancelFeeAppCompleted;
        
        /// <remarks/>
        public event GetCancelReportCompletedEventHandler GetCancelReportCompleted;
        
        /// <remarks/>
        public event GetCheckCompleteCompletedEventHandler GetCheckCompleteCompleted;
        
        /// <remarks/>
        public event GetDictInfoCompletedEventHandler GetDictInfoCompleted;
        
        /// <remarks/>
        public event GetPatInfoToRISCompletedEventHandler GetPatInfoToRISCompleted;
        
        /// <remarks/>
        public event GetPatOrdListCompletedEventHandler GetPatOrdListCompleted;
        
        /// <remarks/>
        public event GetRegInfoCompletedEventHandler GetRegInfoCompleted;
        
        /// <remarks/>
        public event GetReturnReportsCompletedEventHandler GetReturnReportsCompleted;
        
        /// <remarks/>
        public event SendPatOrdListToRisCompletedEventHandler SendPatOrdListToRisCompleted;
        
        /// <remarks/>
        public event StopOrderCompletedEventHandler StopOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetAppForm", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAppForm(string Input) {
            object[] results = this.Invoke("GetAppForm", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAppFormAsync(string Input) {
            this.GetAppFormAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetAppFormAsync(string Input, object userState) {
            if ((this.GetAppFormOperationCompleted == null)) {
                this.GetAppFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppFormOperationCompleted);
            }
            this.InvokeAsync("GetAppForm", new object[] {
                        Input}, this.GetAppFormOperationCompleted, userState);
        }
        
        private void OnGetAppFormOperationCompleted(object arg) {
            if ((this.GetAppFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppFormCompleted(this, new GetAppFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetBookedInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBookedInfo(string Input) {
            object[] results = this.Invoke("GetBookedInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBookedInfoAsync(string Input) {
            this.GetBookedInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetBookedInfoAsync(string Input, object userState) {
            if ((this.GetBookedInfoOperationCompleted == null)) {
                this.GetBookedInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBookedInfoOperationCompleted);
            }
            this.InvokeAsync("GetBookedInfo", new object[] {
                        Input}, this.GetBookedInfoOperationCompleted, userState);
        }
        
        private void OnGetBookedInfoOperationCompleted(object arg) {
            if ((this.GetBookedInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBookedInfoCompleted(this, new GetBookedInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetCancelBookedInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCancelBookedInfo(string Input) {
            object[] results = this.Invoke("GetCancelBookedInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCancelBookedInfoAsync(string Input) {
            this.GetCancelBookedInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetCancelBookedInfoAsync(string Input, object userState) {
            if ((this.GetCancelBookedInfoOperationCompleted == null)) {
                this.GetCancelBookedInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCancelBookedInfoOperationCompleted);
            }
            this.InvokeAsync("GetCancelBookedInfo", new object[] {
                        Input}, this.GetCancelBookedInfoOperationCompleted, userState);
        }
        
        private void OnGetCancelBookedInfoOperationCompleted(object arg) {
            if ((this.GetCancelBookedInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCancelBookedInfoCompleted(this, new GetCancelBookedInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetCancelFeeApp", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCancelFeeApp(string Input) {
            object[] results = this.Invoke("GetCancelFeeApp", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCancelFeeAppAsync(string Input) {
            this.GetCancelFeeAppAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetCancelFeeAppAsync(string Input, object userState) {
            if ((this.GetCancelFeeAppOperationCompleted == null)) {
                this.GetCancelFeeAppOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCancelFeeAppOperationCompleted);
            }
            this.InvokeAsync("GetCancelFeeApp", new object[] {
                        Input}, this.GetCancelFeeAppOperationCompleted, userState);
        }
        
        private void OnGetCancelFeeAppOperationCompleted(object arg) {
            if ((this.GetCancelFeeAppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCancelFeeAppCompleted(this, new GetCancelFeeAppCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetCancelReport", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCancelReport(string Input) {
            object[] results = this.Invoke("GetCancelReport", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCancelReportAsync(string Input) {
            this.GetCancelReportAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetCancelReportAsync(string Input, object userState) {
            if ((this.GetCancelReportOperationCompleted == null)) {
                this.GetCancelReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCancelReportOperationCompleted);
            }
            this.InvokeAsync("GetCancelReport", new object[] {
                        Input}, this.GetCancelReportOperationCompleted, userState);
        }
        
        private void OnGetCancelReportOperationCompleted(object arg) {
            if ((this.GetCancelReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCancelReportCompleted(this, new GetCancelReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetCheckComplete", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCheckComplete(string Input) {
            object[] results = this.Invoke("GetCheckComplete", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCheckCompleteAsync(string Input) {
            this.GetCheckCompleteAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetCheckCompleteAsync(string Input, object userState) {
            if ((this.GetCheckCompleteOperationCompleted == null)) {
                this.GetCheckCompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCheckCompleteOperationCompleted);
            }
            this.InvokeAsync("GetCheckComplete", new object[] {
                        Input}, this.GetCheckCompleteOperationCompleted, userState);
        }
        
        private void OnGetCheckCompleteOperationCompleted(object arg) {
            if ((this.GetCheckCompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCheckCompleteCompleted(this, new GetCheckCompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetDictInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDictInfo(string Input) {
            object[] results = this.Invoke("GetDictInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDictInfoAsync(string Input) {
            this.GetDictInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetDictInfoAsync(string Input, object userState) {
            if ((this.GetDictInfoOperationCompleted == null)) {
                this.GetDictInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDictInfoOperationCompleted);
            }
            this.InvokeAsync("GetDictInfo", new object[] {
                        Input}, this.GetDictInfoOperationCompleted, userState);
        }
        
        private void OnGetDictInfoOperationCompleted(object arg) {
            if ((this.GetDictInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDictInfoCompleted(this, new GetDictInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetPatInfoToRIS", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPatInfoToRIS(string Input) {
            object[] results = this.Invoke("GetPatInfoToRIS", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatInfoToRISAsync(string Input) {
            this.GetPatInfoToRISAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetPatInfoToRISAsync(string Input, object userState) {
            if ((this.GetPatInfoToRISOperationCompleted == null)) {
                this.GetPatInfoToRISOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatInfoToRISOperationCompleted);
            }
            this.InvokeAsync("GetPatInfoToRIS", new object[] {
                        Input}, this.GetPatInfoToRISOperationCompleted, userState);
        }
        
        private void OnGetPatInfoToRISOperationCompleted(object arg) {
            if ((this.GetPatInfoToRISCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatInfoToRISCompleted(this, new GetPatInfoToRISCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetPatOrdList", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPatOrdList(string Input) {
            object[] results = this.Invoke("GetPatOrdList", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPatOrdListAsync(string Input) {
            this.GetPatOrdListAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetPatOrdListAsync(string Input, object userState) {
            if ((this.GetPatOrdListOperationCompleted == null)) {
                this.GetPatOrdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPatOrdListOperationCompleted);
            }
            this.InvokeAsync("GetPatOrdList", new object[] {
                        Input}, this.GetPatOrdListOperationCompleted, userState);
        }
        
        private void OnGetPatOrdListOperationCompleted(object arg) {
            if ((this.GetPatOrdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPatOrdListCompleted(this, new GetPatOrdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetRegInfo", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRegInfo(string Input) {
            object[] results = this.Invoke("GetRegInfo", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRegInfoAsync(string Input) {
            this.GetRegInfoAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetRegInfoAsync(string Input, object userState) {
            if ((this.GetRegInfoOperationCompleted == null)) {
                this.GetRegInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegInfoOperationCompleted);
            }
            this.InvokeAsync("GetRegInfo", new object[] {
                        Input}, this.GetRegInfoOperationCompleted, userState);
        }
        
        private void OnGetRegInfoOperationCompleted(object arg) {
            if ((this.GetRegInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegInfoCompleted(this, new GetRegInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.GetReturnReports", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReturnReports(string Input) {
            object[] results = this.Invoke("GetReturnReports", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReturnReportsAsync(string Input) {
            this.GetReturnReportsAsync(Input, null);
        }
        
        /// <remarks/>
        public void GetReturnReportsAsync(string Input, object userState) {
            if ((this.GetReturnReportsOperationCompleted == null)) {
                this.GetReturnReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReturnReportsOperationCompleted);
            }
            this.InvokeAsync("GetReturnReports", new object[] {
                        Input}, this.GetReturnReportsOperationCompleted, userState);
        }
        
        private void OnGetReturnReportsOperationCompleted(object arg) {
            if ((this.GetReturnReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReturnReportsCompleted(this, new GetReturnReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.SendPatOrdListToRis", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendPatOrdListToRis(string Input) {
            object[] results = this.Invoke("SendPatOrdListToRis", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendPatOrdListToRisAsync(string Input) {
            this.SendPatOrdListToRisAsync(Input, null);
        }
        
        /// <remarks/>
        public void SendPatOrdListToRisAsync(string Input, object userState) {
            if ((this.SendPatOrdListToRisOperationCompleted == null)) {
                this.SendPatOrdListToRisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPatOrdListToRisOperationCompleted);
            }
            this.InvokeAsync("SendPatOrdListToRis", new object[] {
                        Input}, this.SendPatOrdListToRisOperationCompleted, userState);
        }
        
        private void OnSendPatOrdListToRisOperationCompleted(object arg) {
            if ((this.SendPatOrdListToRisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPatOrdListToRisCompleted(this, new SendPatOrdListToRisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DHC.RIS.BS.WebRisService.StopOrder", RequestNamespace="http://tempuri.org", ResponseNamespace="http://tempuri.org", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StopOrder(string Input) {
            object[] results = this.Invoke("StopOrder", new object[] {
                        Input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StopOrderAsync(string Input) {
            this.StopOrderAsync(Input, null);
        }
        
        /// <remarks/>
        public void StopOrderAsync(string Input, object userState) {
            if ((this.StopOrderOperationCompleted == null)) {
                this.StopOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopOrderOperationCompleted);
            }
            this.InvokeAsync("StopOrder", new object[] {
                        Input}, this.StopOrderOperationCompleted, userState);
        }
        
        private void OnStopOrderOperationCompleted(object arg) {
            if ((this.StopOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopOrderCompleted(this, new StopOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetAppFormCompletedEventHandler(object sender, GetAppFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetBookedInfoCompletedEventHandler(object sender, GetBookedInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBookedInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBookedInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCancelBookedInfoCompletedEventHandler(object sender, GetCancelBookedInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCancelBookedInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCancelBookedInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCancelFeeAppCompletedEventHandler(object sender, GetCancelFeeAppCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCancelFeeAppCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCancelFeeAppCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCancelReportCompletedEventHandler(object sender, GetCancelReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCancelReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCancelReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetCheckCompleteCompletedEventHandler(object sender, GetCheckCompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCheckCompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCheckCompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetDictInfoCompletedEventHandler(object sender, GetDictInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDictInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDictInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetPatInfoToRISCompletedEventHandler(object sender, GetPatInfoToRISCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatInfoToRISCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatInfoToRISCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetPatOrdListCompletedEventHandler(object sender, GetPatOrdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPatOrdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPatOrdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetRegInfoCompletedEventHandler(object sender, GetRegInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void GetReturnReportsCompletedEventHandler(object sender, GetReturnReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReturnReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReturnReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void SendPatOrdListToRisCompletedEventHandler(object sender, SendPatOrdListToRisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPatOrdListToRisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPatOrdListToRisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void StopOrderCompletedEventHandler(object sender, StopOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591