//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace LGHISJKZGQ.sh7yweb2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="healthServiceSoap11Binding", Namespace="http://webservice.frame.com.cn")]
    public partial class healthService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getHistoryInfoByStudyidOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHistoryInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConclusionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRadiologicalItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStudyidByRqOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNormalItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStudyidByYyrqOperationCompleted;
        
        private System.Threading.SendOrPostCallback getImagingItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public healthService() {
            this.Url = global::LGHISJKZGQ.Properties.Settings.Default.PATHGETHISZGQ_sh7yweb2_healthService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getHistoryInfoByStudyidCompletedEventHandler getHistoryInfoByStudyidCompleted;
        
        /// <remarks/>
        public event getHistoryInfoCompletedEventHandler getHistoryInfoCompleted;
        
        /// <remarks/>
        public event getConclusionCompletedEventHandler getConclusionCompleted;
        
        /// <remarks/>
        public event getRadiologicalItemsCompletedEventHandler getRadiologicalItemsCompleted;
        
        /// <remarks/>
        public event getStudyidByRqCompletedEventHandler getStudyidByRqCompleted;
        
        /// <remarks/>
        public event getNormalItemsCompletedEventHandler getNormalItemsCompleted;
        
        /// <remarks/>
        public event getStudyidByYyrqCompletedEventHandler getStudyidByYyrqCompleted;
        
        /// <remarks/>
        public event getImagingItemsCompletedEventHandler getImagingItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getHistoryInfoByStudyid", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public PersonInfo getHistoryInfoByStudyid([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid) {
            object[] results = this.Invoke("getHistoryInfoByStudyid", new object[] {
                        studyid});
            return ((PersonInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getHistoryInfoByStudyidAsync(string studyid) {
            this.getHistoryInfoByStudyidAsync(studyid, null);
        }
        
        /// <remarks/>
        public void getHistoryInfoByStudyidAsync(string studyid, object userState) {
            if ((this.getHistoryInfoByStudyidOperationCompleted == null)) {
                this.getHistoryInfoByStudyidOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHistoryInfoByStudyidOperationCompleted);
            }
            this.InvokeAsync("getHistoryInfoByStudyid", new object[] {
                        studyid}, this.getHistoryInfoByStudyidOperationCompleted, userState);
        }
        
        private void OngetHistoryInfoByStudyidOperationCompleted(object arg) {
            if ((this.getHistoryInfoByStudyidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHistoryInfoByStudyidCompleted(this, new getHistoryInfoByStudyidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getHistoryInfo", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public PersonInfo[] getHistoryInfo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string identityNum, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string telephone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cardno) {
            object[] results = this.Invoke("getHistoryInfo", new object[] {
                        name,
                        identityNum,
                        studyid,
                        telephone,
                        cardno});
            return ((PersonInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void getHistoryInfoAsync(string name, string identityNum, string studyid, string telephone, string cardno) {
            this.getHistoryInfoAsync(name, identityNum, studyid, telephone, cardno, null);
        }
        
        /// <remarks/>
        public void getHistoryInfoAsync(string name, string identityNum, string studyid, string telephone, string cardno, object userState) {
            if ((this.getHistoryInfoOperationCompleted == null)) {
                this.getHistoryInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHistoryInfoOperationCompleted);
            }
            this.InvokeAsync("getHistoryInfo", new object[] {
                        name,
                        identityNum,
                        studyid,
                        telephone,
                        cardno}, this.getHistoryInfoOperationCompleted, userState);
        }
        
        private void OngetHistoryInfoOperationCompleted(object arg) {
            if ((this.getHistoryInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHistoryInfoCompleted(this, new getHistoryInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getConclusion", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Conclusion getConclusion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid) {
            object[] results = this.Invoke("getConclusion", new object[] {
                        studyid});
            return ((Conclusion)(results[0]));
        }
        
        /// <remarks/>
        public void getConclusionAsync(string studyid) {
            this.getConclusionAsync(studyid, null);
        }
        
        /// <remarks/>
        public void getConclusionAsync(string studyid, object userState) {
            if ((this.getConclusionOperationCompleted == null)) {
                this.getConclusionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConclusionOperationCompleted);
            }
            this.InvokeAsync("getConclusion", new object[] {
                        studyid}, this.getConclusionOperationCompleted, userState);
        }
        
        private void OngetConclusionOperationCompleted(object arg) {
            if ((this.getConclusionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConclusionCompleted(this, new getConclusionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getRadiologicalItems", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public ImagingItem[] getRadiologicalItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid) {
            object[] results = this.Invoke("getRadiologicalItems", new object[] {
                        studyid});
            return ((ImagingItem[])(results[0]));
        }
        
        /// <remarks/>
        public void getRadiologicalItemsAsync(string studyid) {
            this.getRadiologicalItemsAsync(studyid, null);
        }
        
        /// <remarks/>
        public void getRadiologicalItemsAsync(string studyid, object userState) {
            if ((this.getRadiologicalItemsOperationCompleted == null)) {
                this.getRadiologicalItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRadiologicalItemsOperationCompleted);
            }
            this.InvokeAsync("getRadiologicalItems", new object[] {
                        studyid}, this.getRadiologicalItemsOperationCompleted, userState);
        }
        
        private void OngetRadiologicalItemsOperationCompleted(object arg) {
            if ((this.getRadiologicalItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRadiologicalItemsCompleted(this, new getRadiologicalItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getStudyidByRq", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public object getStudyidByRq([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string startTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string endTime) {
            object[] results = this.Invoke("getStudyidByRq", new object[] {
                        startTime,
                        endTime});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void getStudyidByRqAsync(string startTime, string endTime) {
            this.getStudyidByRqAsync(startTime, endTime, null);
        }
        
        /// <remarks/>
        public void getStudyidByRqAsync(string startTime, string endTime, object userState) {
            if ((this.getStudyidByRqOperationCompleted == null)) {
                this.getStudyidByRqOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStudyidByRqOperationCompleted);
            }
            this.InvokeAsync("getStudyidByRq", new object[] {
                        startTime,
                        endTime}, this.getStudyidByRqOperationCompleted, userState);
        }
        
        private void OngetStudyidByRqOperationCompleted(object arg) {
            if ((this.getStudyidByRqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStudyidByRqCompleted(this, new getStudyidByRqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getNormalItems", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public NormalItem[] getNormalItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid) {
            object[] results = this.Invoke("getNormalItems", new object[] {
                        studyid});
            return ((NormalItem[])(results[0]));
        }
        
        /// <remarks/>
        public void getNormalItemsAsync(string studyid) {
            this.getNormalItemsAsync(studyid, null);
        }
        
        /// <remarks/>
        public void getNormalItemsAsync(string studyid, object userState) {
            if ((this.getNormalItemsOperationCompleted == null)) {
                this.getNormalItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNormalItemsOperationCompleted);
            }
            this.InvokeAsync("getNormalItems", new object[] {
                        studyid}, this.getNormalItemsOperationCompleted, userState);
        }
        
        private void OngetNormalItemsOperationCompleted(object arg) {
            if ((this.getNormalItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNormalItemsCompleted(this, new getNormalItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getStudyidByYyrq", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string getStudyidByYyrq([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string startTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string endTime) {
            object[] results = this.Invoke("getStudyidByYyrq", new object[] {
                        startTime,
                        endTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStudyidByYyrqAsync(string startTime, string endTime) {
            this.getStudyidByYyrqAsync(startTime, endTime, null);
        }
        
        /// <remarks/>
        public void getStudyidByYyrqAsync(string startTime, string endTime, object userState) {
            if ((this.getStudyidByYyrqOperationCompleted == null)) {
                this.getStudyidByYyrqOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStudyidByYyrqOperationCompleted);
            }
            this.InvokeAsync("getStudyidByYyrq", new object[] {
                        startTime,
                        endTime}, this.getStudyidByYyrqOperationCompleted, userState);
        }
        
        private void OngetStudyidByYyrqOperationCompleted(object arg) {
            if ((this.getStudyidByYyrqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStudyidByYyrqCompleted(this, new getStudyidByYyrqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getImagingItems", RequestNamespace="http://webservice.frame.com.cn", ResponseNamespace="http://webservice.frame.com.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public ImagingItem[] getImagingItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string studyid) {
            object[] results = this.Invoke("getImagingItems", new object[] {
                        studyid});
            return ((ImagingItem[])(results[0]));
        }
        
        /// <remarks/>
        public void getImagingItemsAsync(string studyid) {
            this.getImagingItemsAsync(studyid, null);
        }
        
        /// <remarks/>
        public void getImagingItemsAsync(string studyid, object userState) {
            if ((this.getImagingItemsOperationCompleted == null)) {
                this.getImagingItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetImagingItemsOperationCompleted);
            }
            this.InvokeAsync("getImagingItems", new object[] {
                        studyid}, this.getImagingItemsOperationCompleted, userState);
        }
        
        private void OngetImagingItemsOperationCompleted(object arg) {
            if ((this.getImagingItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getImagingItemsCompleted(this, new getImagingItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entity.frame.com.cn/xsd")]
    public partial class PersonInfo {
        
        private System.Nullable<int> ageField;
        
        private bool ageFieldSpecified;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string cardnoField;
        
        private string companyNameField;
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string identityNumField;
        
        private string itemjsonField;
        
        private string nameField;
        
        private string sexField;
        
        private string studyidField;
        
        private string telephoneField;
        
        private System.Nullable<int> wcbzField;
        
        private bool wcbzFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> age {
            get {
                return this.ageField;
            }
            set {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ageSpecified {
            get {
                return this.ageFieldSpecified;
            }
            set {
                this.ageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cardno {
            get {
                return this.cardnoField;
            }
            set {
                this.cardnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string identityNum {
            get {
                return this.identityNumField;
            }
            set {
                this.identityNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemjson {
            get {
                return this.itemjsonField;
            }
            set {
                this.itemjsonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string studyid {
            get {
                return this.studyidField;
            }
            set {
                this.studyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> wcbz {
            get {
                return this.wcbzField;
            }
            set {
                this.wcbzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wcbzSpecified {
            get {
                return this.wcbzFieldSpecified;
            }
            set {
                this.wcbzFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entity.frame.com.cn/xsd")]
    public partial class NormalItem {
        
        private System.Nullable<System.DateTime> dateField;
        
        private bool dateFieldSpecified;
        
        private string defvalueField;
        
        private string departmentNameField;
        
        private string departmentReportField;
        
        private System.Nullable<int> departmentTypeField;
        
        private bool departmentTypeFieldSpecified;
        
        private string doctorField;
        
        private string itemField;
        
        private string positiveFlagField;
        
        private string resultField;
        
        private string sampleNameField;
        
        private string sampleTypeField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string defvalue {
            get {
                return this.defvalueField;
            }
            set {
                this.defvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string departmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string departmentReport {
            get {
                return this.departmentReportField;
            }
            set {
                this.departmentReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> departmentType {
            get {
                return this.departmentTypeField;
            }
            set {
                this.departmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departmentTypeSpecified {
            get {
                return this.departmentTypeFieldSpecified;
            }
            set {
                this.departmentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doctor {
            get {
                return this.doctorField;
            }
            set {
                this.doctorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string positiveFlag {
            get {
                return this.positiveFlagField;
            }
            set {
                this.positiveFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sampleName {
            get {
                return this.sampleNameField;
            }
            set {
                this.sampleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sampleType {
            get {
                return this.sampleTypeField;
            }
            set {
                this.sampleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entity.frame.com.cn/xsd")]
    public partial class ImagingItem {
        
        private string departmentNameField;
        
        private System.Nullable<int> departmentTypeField;
        
        private bool departmentTypeFieldSpecified;
        
        private string descriptionField;
        
        private string doctorField;
        
        private string numField;
        
        private string remoteFileField;
        
        private string[] remoteFilesField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string departmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> departmentType {
            get {
                return this.departmentTypeField;
            }
            set {
                this.departmentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departmentTypeSpecified {
            get {
                return this.departmentTypeFieldSpecified;
            }
            set {
                this.departmentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doctor {
            get {
                return this.doctorField;
            }
            set {
                this.doctorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string remoteFile {
            get {
                return this.remoteFileField;
            }
            set {
                this.remoteFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("remoteFiles", IsNullable=true)]
        public string[] remoteFiles {
            get {
                return this.remoteFilesField;
            }
            set {
                this.remoteFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://entity.frame.com.cn/xsd")]
    public partial class Conclusion {
        
        private string conclusionField;
        
        private string doctorField;
        
        private string healthCareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string conclusion {
            get {
                return this.conclusionField;
            }
            set {
                this.conclusionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doctor {
            get {
                return this.doctorField;
            }
            set {
                this.doctorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string healthCare {
            get {
                return this.healthCareField;
            }
            set {
                this.healthCareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getHistoryInfoByStudyidCompletedEventHandler(object sender, getHistoryInfoByStudyidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHistoryInfoByStudyidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHistoryInfoByStudyidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getHistoryInfoCompletedEventHandler(object sender, getHistoryInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHistoryInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHistoryInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PersonInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PersonInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getConclusionCompletedEventHandler(object sender, getConclusionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConclusionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConclusionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Conclusion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Conclusion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getRadiologicalItemsCompletedEventHandler(object sender, getRadiologicalItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRadiologicalItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRadiologicalItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImagingItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImagingItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getStudyidByRqCompletedEventHandler(object sender, getStudyidByRqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStudyidByRqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStudyidByRqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getNormalItemsCompletedEventHandler(object sender, getNormalItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNormalItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNormalItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NormalItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NormalItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getStudyidByYyrqCompletedEventHandler(object sender, getStudyidByYyrqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStudyidByYyrqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStudyidByYyrqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getImagingItemsCompletedEventHandler(object sender, getImagingItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getImagingItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getImagingItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ImagingItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ImagingItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591