//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace PathHISZGQJK.cszxyyweb2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NYwclServiceSoapBinding", Namespace="http://ihis.pub.ws")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BeansException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Exception))]
    public partial class NYwclService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback syncbusiOperationCompleted;
        
        private System.Threading.SendOrPostCallback sqlselectOperationCompleted;
        
        private System.Threading.SendOrPostCallback businessOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBitMatrixOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadWithByteOperationCompleted;
        
        private System.Threading.SendOrPostCallback asyncbusiOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadToThxOperationCompleted;
        
        private System.Threading.SendOrPostCallback asyncselectOperationCompleted;
        
        private System.Threading.SendOrPostCallback emrGetBsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getXmlFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback bselectWithTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetJcjgbOperationCompleted;
        
        private System.Threading.SendOrPostCallback updatePicOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback singleSelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTodayOperationCompleted;
        
        private System.Threading.SendOrPostCallback bselectOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadGrqmOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetxmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback gettyPicOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPicOperationCompleted;
        
        private System.Threading.SendOrPostCallback StaticSelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback pselectOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTxmOperationCompleted;
        
        private System.Threading.SendOrPostCallback setApplicationContextOperationCompleted;
        
        private System.Threading.SendOrPostCallback getglbmOperationCompleted;
        
        private System.Threading.SendOrPostCallback uploadToServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMd5MOperationCompleted;
        
        private System.Threading.SendOrPostCallback downFromServerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NYwclService() {
            this.Url = global::PathHISZGQJK.Properties.Settings.Default.PathHISZGQJK_cszxyyweb2_NYwclService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event syncbusiCompletedEventHandler syncbusiCompleted;
        
        /// <remarks/>
        public event sqlselectCompletedEventHandler sqlselectCompleted;
        
        /// <remarks/>
        public event businessCompletedEventHandler businessCompleted;
        
        /// <remarks/>
        public event getBitMatrixCompletedEventHandler getBitMatrixCompleted;
        
        /// <remarks/>
        public event uploadWithByteCompletedEventHandler uploadWithByteCompleted;
        
        /// <remarks/>
        public event asyncbusiCompletedEventHandler asyncbusiCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event uploadToThxCompletedEventHandler uploadToThxCompleted;
        
        /// <remarks/>
        public event asyncselectCompletedEventHandler asyncselectCompleted;
        
        /// <remarks/>
        public event emrGetBsCompletedEventHandler emrGetBsCompleted;
        
        /// <remarks/>
        public event getXmlFileCompletedEventHandler getXmlFileCompleted;
        
        /// <remarks/>
        public event bselectWithTimeCompletedEventHandler bselectWithTimeCompleted;
        
        /// <remarks/>
        public event SetJcjgbCompletedEventHandler SetJcjgbCompleted;
        
        /// <remarks/>
        public event updatePicCompletedEventHandler updatePicCompleted;
        
        /// <remarks/>
        public event uploadfileCompletedEventHandler uploadfileCompleted;
        
        /// <remarks/>
        public event singleSelectCompletedEventHandler singleSelectCompleted;
        
        /// <remarks/>
        public event getTodayCompletedEventHandler getTodayCompleted;
        
        /// <remarks/>
        public event bselectCompletedEventHandler bselectCompleted;
        
        /// <remarks/>
        public event uploadGrqmCompletedEventHandler uploadGrqmCompleted;
        
        /// <remarks/>
        public event GetxmlCompletedEventHandler GetxmlCompleted;
        
        /// <remarks/>
        public event gettyPicCompletedEventHandler gettyPicCompleted;
        
        /// <remarks/>
        public event getPicCompletedEventHandler getPicCompleted;
        
        /// <remarks/>
        public event StaticSelectCompletedEventHandler StaticSelectCompleted;
        
        /// <remarks/>
        public event pselectCompletedEventHandler pselectCompleted;
        
        /// <remarks/>
        public event getTxmCompletedEventHandler getTxmCompleted;
        
        /// <remarks/>
        public event setApplicationContextCompletedEventHandler setApplicationContextCompleted;
        
        /// <remarks/>
        public event getglbmCompletedEventHandler getglbmCompleted;
        
        /// <remarks/>
        public event uploadToServerCompletedEventHandler uploadToServerCompleted;
        
        /// <remarks/>
        public event getMd5MCompletedEventHandler getMd5MCompleted;
        
        /// <remarks/>
        public event downFromServerCompletedEventHandler downFromServerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string syncbusi(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            object[] results = this.Invoke("syncbusi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void syncbusiAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            this.syncbusiAsync(arg0, arg1, arg2, arg3, arg4, arg5, arg6, null);
        }
        
        /// <remarks/>
        public void syncbusiAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6, object userState) {
            if ((this.syncbusiOperationCompleted == null)) {
                this.syncbusiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncbusiOperationCompleted);
            }
            this.InvokeAsync("syncbusi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6}, this.syncbusiOperationCompleted, userState);
        }
        
        private void OnsyncbusiOperationCompleted(object arg) {
            if ((this.syncbusiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncbusiCompleted(this, new syncbusiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string sqlselect(int arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("sqlselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sqlselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4) {
            this.sqlselectAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void sqlselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.sqlselectOperationCompleted == null)) {
                this.sqlselectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsqlselectOperationCompleted);
            }
            this.InvokeAsync("sqlselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.sqlselectOperationCompleted, userState);
        }
        
        private void OnsqlselectOperationCompleted(object arg) {
            if ((this.sqlselectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sqlselectCompleted(this, new sqlselectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string business(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            object[] results = this.Invoke("business", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void businessAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            this.businessAsync(arg0, arg1, arg2, arg3, arg4, arg5, arg6, null);
        }
        
        /// <remarks/>
        public void businessAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6, object userState) {
            if ((this.businessOperationCompleted == null)) {
                this.businessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbusinessOperationCompleted);
            }
            this.InvokeAsync("business", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6}, this.businessOperationCompleted, userState);
        }
        
        private void OnbusinessOperationCompleted(object arg) {
            if ((this.businessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.businessCompleted(this, new businessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] getBitMatrix(string arg0, int arg1, int arg2) {
            object[] results = this.Invoke("getBitMatrix", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getBitMatrixAsync(string arg0, int arg1, int arg2) {
            this.getBitMatrixAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getBitMatrixAsync(string arg0, int arg1, int arg2, object userState) {
            if ((this.getBitMatrixOperationCompleted == null)) {
                this.getBitMatrixOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBitMatrixOperationCompleted);
            }
            this.InvokeAsync("getBitMatrix", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getBitMatrixOperationCompleted, userState);
        }
        
        private void OngetBitMatrixOperationCompleted(object arg) {
            if ((this.getBitMatrixCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBitMatrixCompleted(this, new getBitMatrixCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string uploadWithByte([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("uploadWithByte", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadWithByteAsync(byte[] arg0, string arg1, string arg2, string arg3, string arg4) {
            this.uploadWithByteAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void uploadWithByteAsync(byte[] arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.uploadWithByteOperationCompleted == null)) {
                this.uploadWithByteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadWithByteOperationCompleted);
            }
            this.InvokeAsync("uploadWithByte", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.uploadWithByteOperationCompleted, userState);
        }
        
        private void OnuploadWithByteOperationCompleted(object arg) {
            if ((this.uploadWithByteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadWithByteCompleted(this, new uploadWithByteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string asyncbusi(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            object[] results = this.Invoke("asyncbusi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void asyncbusiAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6) {
            this.asyncbusiAsync(arg0, arg1, arg2, arg3, arg4, arg5, arg6, null);
        }
        
        /// <remarks/>
        public void asyncbusiAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, string arg6, object userState) {
            if ((this.asyncbusiOperationCompleted == null)) {
                this.asyncbusiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnasyncbusiOperationCompleted);
            }
            this.InvokeAsync("asyncbusi", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6}, this.asyncbusiOperationCompleted, userState);
        }
        
        private void OnasyncbusiOperationCompleted(object arg) {
            if ((this.asyncbusiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.asyncbusiCompleted(this, new asyncbusiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string login(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            object[] results = this.Invoke("login", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5) {
            this.loginAsync(arg0, arg1, arg2, arg3, arg4, arg5, null);
        }
        
        /// <remarks/>
        public void loginAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string uploadToThx([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arg0, string arg1, string arg2, string arg3) {
            object[] results = this.Invoke("uploadToThx", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadToThxAsync(byte[] arg0, string arg1, string arg2, string arg3) {
            this.uploadToThxAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void uploadToThxAsync(byte[] arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.uploadToThxOperationCompleted == null)) {
                this.uploadToThxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadToThxOperationCompleted);
            }
            this.InvokeAsync("uploadToThx", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.uploadToThxOperationCompleted, userState);
        }
        
        private void OnuploadToThxOperationCompleted(object arg) {
            if ((this.uploadToThxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadToThxCompleted(this, new uploadToThxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string asyncselect(int arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("asyncselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void asyncselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4) {
            this.asyncselectAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void asyncselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.asyncselectOperationCompleted == null)) {
                this.asyncselectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnasyncselectOperationCompleted);
            }
            this.InvokeAsync("asyncselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.asyncselectOperationCompleted, userState);
        }
        
        private void OnasyncselectOperationCompleted(object arg) {
            if ((this.asyncselectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.asyncselectCompleted(this, new asyncselectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string emrGetBs(int arg0, string arg1, string arg2) {
            object[] results = this.Invoke("emrGetBs", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void emrGetBsAsync(int arg0, string arg1, string arg2) {
            this.emrGetBsAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void emrGetBsAsync(int arg0, string arg1, string arg2, object userState) {
            if ((this.emrGetBsOperationCompleted == null)) {
                this.emrGetBsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnemrGetBsOperationCompleted);
            }
            this.InvokeAsync("emrGetBs", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.emrGetBsOperationCompleted, userState);
        }
        
        private void OnemrGetBsOperationCompleted(object arg) {
            if ((this.emrGetBsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.emrGetBsCompleted(this, new emrGetBsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getXmlFile(string arg0, string arg1, string arg2) {
            object[] results = this.Invoke("getXmlFile", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getXmlFileAsync(string arg0, string arg1, string arg2) {
            this.getXmlFileAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getXmlFileAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getXmlFileOperationCompleted == null)) {
                this.getXmlFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetXmlFileOperationCompleted);
            }
            this.InvokeAsync("getXmlFile", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getXmlFileOperationCompleted, userState);
        }
        
        private void OngetXmlFileOperationCompleted(object arg) {
            if ((this.getXmlFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getXmlFileCompleted(this, new getXmlFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string bselectWithTime(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            object[] results = this.Invoke("bselectWithTime", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void bselectWithTimeAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            this.bselectWithTimeAsync(arg0, arg1, arg2, arg3, arg4, arg5, null);
        }
        
        /// <remarks/>
        public void bselectWithTimeAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, object userState) {
            if ((this.bselectWithTimeOperationCompleted == null)) {
                this.bselectWithTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbselectWithTimeOperationCompleted);
            }
            this.InvokeAsync("bselectWithTime", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5}, this.bselectWithTimeOperationCompleted, userState);
        }
        
        private void OnbselectWithTimeOperationCompleted(object arg) {
            if ((this.bselectWithTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bselectWithTimeCompleted(this, new bselectWithTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string SetJcjgb(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            object[] results = this.Invoke("SetJcjgb", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetJcjgbAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6) {
            this.SetJcjgbAsync(arg0, arg1, arg2, arg3, arg4, arg5, arg6, null);
        }
        
        /// <remarks/>
        public void SetJcjgbAsync(string arg0, string arg1, string arg2, string arg3, string arg4, string arg5, string arg6, object userState) {
            if ((this.SetJcjgbOperationCompleted == null)) {
                this.SetJcjgbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetJcjgbOperationCompleted);
            }
            this.InvokeAsync("SetJcjgb", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5,
                        arg6}, this.SetJcjgbOperationCompleted, userState);
        }
        
        private void OnSetJcjgbOperationCompleted(object arg) {
            if ((this.SetJcjgbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetJcjgbCompleted(this, new SetJcjgbCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool updatePic(string arg0, string arg1, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arg2) {
            object[] results = this.Invoke("updatePic", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updatePicAsync(string arg0, string arg1, byte[] arg2) {
            this.updatePicAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void updatePicAsync(string arg0, string arg1, byte[] arg2, object userState) {
            if ((this.updatePicOperationCompleted == null)) {
                this.updatePicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdatePicOperationCompleted);
            }
            this.InvokeAsync("updatePic", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.updatePicOperationCompleted, userState);
        }
        
        private void OnupdatePicOperationCompleted(object arg) {
            if ((this.updatePicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updatePicCompleted(this, new updatePicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string uploadfile(string sclx, string swjbt, string swjm, string sscr, string surl, string swid, string sywb, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] wjnr) {
            object[] results = this.Invoke("uploadfile", new object[] {
                        sclx,
                        swjbt,
                        swjm,
                        sscr,
                        surl,
                        swid,
                        sywb,
                        wjnr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadfileAsync(string sclx, string swjbt, string swjm, string sscr, string surl, string swid, string sywb, byte[] wjnr) {
            this.uploadfileAsync(sclx, swjbt, swjm, sscr, surl, swid, sywb, wjnr, null);
        }
        
        /// <remarks/>
        public void uploadfileAsync(string sclx, string swjbt, string swjm, string sscr, string surl, string swid, string sywb, byte[] wjnr, object userState) {
            if ((this.uploadfileOperationCompleted == null)) {
                this.uploadfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadfileOperationCompleted);
            }
            this.InvokeAsync("uploadfile", new object[] {
                        sclx,
                        swjbt,
                        swjm,
                        sscr,
                        surl,
                        swid,
                        sywb,
                        wjnr}, this.uploadfileOperationCompleted, userState);
        }
        
        private void OnuploadfileOperationCompleted(object arg) {
            if ((this.uploadfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadfileCompleted(this, new uploadfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string singleSelect(int arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("singleSelect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void singleSelectAsync(int arg0, string arg1, string arg2, string arg3, string arg4) {
            this.singleSelectAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void singleSelectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.singleSelectOperationCompleted == null)) {
                this.singleSelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsingleSelectOperationCompleted);
            }
            this.InvokeAsync("singleSelect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.singleSelectOperationCompleted, userState);
        }
        
        private void OnsingleSelectOperationCompleted(object arg) {
            if ((this.singleSelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.singleSelectCompleted(this, new singleSelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getToday() {
            object[] results = this.Invoke("getToday", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTodayAsync() {
            this.getTodayAsync(null);
        }
        
        /// <remarks/>
        public void getTodayAsync(object userState) {
            if ((this.getTodayOperationCompleted == null)) {
                this.getTodayOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTodayOperationCompleted);
            }
            this.InvokeAsync("getToday", new object[0], this.getTodayOperationCompleted, userState);
        }
        
        private void OngetTodayOperationCompleted(object arg) {
            if ((this.getTodayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTodayCompleted(this, new getTodayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string bselect(int arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("bselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void bselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4) {
            this.bselectAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void bselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.bselectOperationCompleted == null)) {
                this.bselectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbselectOperationCompleted);
            }
            this.InvokeAsync("bselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.bselectOperationCompleted, userState);
        }
        
        private void OnbselectOperationCompleted(object arg) {
            if ((this.bselectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bselectCompleted(this, new bselectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool uploadGrqm([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arg0, string arg1, string arg2, string arg3) {
            object[] results = this.Invoke("uploadGrqm", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void uploadGrqmAsync(byte[] arg0, string arg1, string arg2, string arg3) {
            this.uploadGrqmAsync(arg0, arg1, arg2, arg3, null);
        }
        
        /// <remarks/>
        public void uploadGrqmAsync(byte[] arg0, string arg1, string arg2, string arg3, object userState) {
            if ((this.uploadGrqmOperationCompleted == null)) {
                this.uploadGrqmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadGrqmOperationCompleted);
            }
            this.InvokeAsync("uploadGrqm", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3}, this.uploadGrqmOperationCompleted, userState);
        }
        
        private void OnuploadGrqmOperationCompleted(object arg) {
            if ((this.uploadGrqmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadGrqmCompleted(this, new uploadGrqmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string Getxml(string arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("Getxml", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetxmlAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.GetxmlAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void GetxmlAsync(string arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.GetxmlOperationCompleted == null)) {
                this.GetxmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetxmlOperationCompleted);
            }
            this.InvokeAsync("Getxml", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.GetxmlOperationCompleted, userState);
        }
        
        private void OnGetxmlOperationCompleted(object arg) {
            if ((this.GetxmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetxmlCompleted(this, new GetxmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] gettyPic(string arg0, string arg1) {
            object[] results = this.Invoke("gettyPic", new object[] {
                        arg0,
                        arg1});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void gettyPicAsync(string arg0, string arg1) {
            this.gettyPicAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void gettyPicAsync(string arg0, string arg1, object userState) {
            if ((this.gettyPicOperationCompleted == null)) {
                this.gettyPicOperationCompleted = new System.Threading.SendOrPostCallback(this.OngettyPicOperationCompleted);
            }
            this.InvokeAsync("gettyPic", new object[] {
                        arg0,
                        arg1}, this.gettyPicOperationCompleted, userState);
        }
        
        private void OngettyPicOperationCompleted(object arg) {
            if ((this.gettyPicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gettyPicCompleted(this, new gettyPicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] getPic(string arg0, string arg1) {
            object[] results = this.Invoke("getPic", new object[] {
                        arg0,
                        arg1});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getPicAsync(string arg0, string arg1) {
            this.getPicAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getPicAsync(string arg0, string arg1, object userState) {
            if ((this.getPicOperationCompleted == null)) {
                this.getPicOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPicOperationCompleted);
            }
            this.InvokeAsync("getPic", new object[] {
                        arg0,
                        arg1}, this.getPicOperationCompleted, userState);
        }
        
        private void OngetPicOperationCompleted(object arg) {
            if ((this.getPicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPicCompleted(this, new getPicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string StaticSelect(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            object[] results = this.Invoke("StaticSelect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StaticSelectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5) {
            this.StaticSelectAsync(arg0, arg1, arg2, arg3, arg4, arg5, null);
        }
        
        /// <remarks/>
        public void StaticSelectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, int arg5, object userState) {
            if ((this.StaticSelectOperationCompleted == null)) {
                this.StaticSelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStaticSelectOperationCompleted);
            }
            this.InvokeAsync("StaticSelect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4,
                        arg5}, this.StaticSelectOperationCompleted, userState);
        }
        
        private void OnStaticSelectOperationCompleted(object arg) {
            if ((this.StaticSelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StaticSelectCompleted(this, new StaticSelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string pselect(int arg0, string arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("pselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4) {
            this.pselectAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void pselectAsync(int arg0, string arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.pselectOperationCompleted == null)) {
                this.pselectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpselectOperationCompleted);
            }
            this.InvokeAsync("pselect", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.pselectOperationCompleted, userState);
        }
        
        private void OnpselectOperationCompleted(object arg) {
            if ((this.pselectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pselectCompleted(this, new pselectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] getTxm(string arg0, int arg1) {
            object[] results = this.Invoke("getTxm", new object[] {
                        arg0,
                        arg1});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getTxmAsync(string arg0, int arg1) {
            this.getTxmAsync(arg0, arg1, null);
        }
        
        /// <remarks/>
        public void getTxmAsync(string arg0, int arg1, object userState) {
            if ((this.getTxmOperationCompleted == null)) {
                this.getTxmOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTxmOperationCompleted);
            }
            this.InvokeAsync("getTxm", new object[] {
                        arg0,
                        arg1}, this.getTxmOperationCompleted, userState);
        }
        
        private void OngetTxmOperationCompleted(object arg) {
            if ((this.getTxmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTxmCompleted(this, new getTxmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public void setApplicationContext(object arg0) {
            this.Invoke("setApplicationContext", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public void setApplicationContextAsync(object arg0) {
            this.setApplicationContextAsync(arg0, null);
        }
        
        /// <remarks/>
        public void setApplicationContextAsync(object arg0, object userState) {
            if ((this.setApplicationContextOperationCompleted == null)) {
                this.setApplicationContextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetApplicationContextOperationCompleted);
            }
            this.InvokeAsync("setApplicationContext", new object[] {
                        arg0}, this.setApplicationContextOperationCompleted, userState);
        }
        
        private void OnsetApplicationContextOperationCompleted(object arg) {
            if ((this.setApplicationContextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setApplicationContextCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getglbm(string arg0, string arg1, string arg2) {
            object[] results = this.Invoke("getglbm", new object[] {
                        arg0,
                        arg1,
                        arg2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getglbmAsync(string arg0, string arg1, string arg2) {
            this.getglbmAsync(arg0, arg1, arg2, null);
        }
        
        /// <remarks/>
        public void getglbmAsync(string arg0, string arg1, string arg2, object userState) {
            if ((this.getglbmOperationCompleted == null)) {
                this.getglbmOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetglbmOperationCompleted);
            }
            this.InvokeAsync("getglbm", new object[] {
                        arg0,
                        arg1,
                        arg2}, this.getglbmOperationCompleted, userState);
        }
        
        private void OngetglbmOperationCompleted(object arg) {
            if ((this.getglbmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getglbmCompleted(this, new getglbmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string uploadToServer(string arg0, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] arg1, string arg2, string arg3, string arg4) {
            object[] results = this.Invoke("uploadToServer", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uploadToServerAsync(string arg0, byte[] arg1, string arg2, string arg3, string arg4) {
            this.uploadToServerAsync(arg0, arg1, arg2, arg3, arg4, null);
        }
        
        /// <remarks/>
        public void uploadToServerAsync(string arg0, byte[] arg1, string arg2, string arg3, string arg4, object userState) {
            if ((this.uploadToServerOperationCompleted == null)) {
                this.uploadToServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadToServerOperationCompleted);
            }
            this.InvokeAsync("uploadToServer", new object[] {
                        arg0,
                        arg1,
                        arg2,
                        arg3,
                        arg4}, this.uploadToServerOperationCompleted, userState);
        }
        
        private void OnuploadToServerOperationCompleted(object arg) {
            if ((this.uploadToServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadToServerCompleted(this, new uploadToServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getMd5M(string arg0) {
            object[] results = this.Invoke("getMd5M", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMd5MAsync(string arg0) {
            this.getMd5MAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getMd5MAsync(string arg0, object userState) {
            if ((this.getMd5MOperationCompleted == null)) {
                this.getMd5MOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMd5MOperationCompleted);
            }
            this.InvokeAsync("getMd5M", new object[] {
                        arg0}, this.getMd5MOperationCompleted, userState);
        }
        
        private void OngetMd5MOperationCompleted(object arg) {
            if ((this.getMd5MCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMd5MCompleted(this, new getMd5MCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://ihis.pub.ws", ResponseNamespace="http://ihis.pub.ws", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="base64Binary")]
        public byte[] downFromServer(string arg0) {
            object[] results = this.Invoke("downFromServer", new object[] {
                        arg0});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void downFromServerAsync(string arg0) {
            this.downFromServerAsync(arg0, null);
        }
        
        /// <remarks/>
        public void downFromServerAsync(string arg0, object userState) {
            if ((this.downFromServerOperationCompleted == null)) {
                this.downFromServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OndownFromServerOperationCompleted);
            }
            this.InvokeAsync("downFromServer", new object[] {
                        arg0}, this.downFromServerOperationCompleted, userState);
        }
        
        private void OndownFromServerOperationCompleted(object arg) {
            if ((this.downFromServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.downFromServerCompleted(this, new downFromServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ihis.pub.ws")]
    public partial class BeansException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ihis.pub.ws")]
    public partial class Exception {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void syncbusiCompletedEventHandler(object sender, syncbusiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncbusiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncbusiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void sqlselectCompletedEventHandler(object sender, sqlselectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sqlselectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sqlselectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void businessCompletedEventHandler(object sender, businessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class businessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal businessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getBitMatrixCompletedEventHandler(object sender, getBitMatrixCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBitMatrixCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBitMatrixCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void uploadWithByteCompletedEventHandler(object sender, uploadWithByteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadWithByteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadWithByteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void asyncbusiCompletedEventHandler(object sender, asyncbusiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class asyncbusiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal asyncbusiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void uploadToThxCompletedEventHandler(object sender, uploadToThxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadToThxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadToThxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void asyncselectCompletedEventHandler(object sender, asyncselectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class asyncselectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal asyncselectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void emrGetBsCompletedEventHandler(object sender, emrGetBsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class emrGetBsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal emrGetBsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getXmlFileCompletedEventHandler(object sender, getXmlFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getXmlFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getXmlFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bselectWithTimeCompletedEventHandler(object sender, bselectWithTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bselectWithTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bselectWithTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetJcjgbCompletedEventHandler(object sender, SetJcjgbCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetJcjgbCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetJcjgbCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updatePicCompletedEventHandler(object sender, updatePicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updatePicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updatePicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void uploadfileCompletedEventHandler(object sender, uploadfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void singleSelectCompletedEventHandler(object sender, singleSelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class singleSelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal singleSelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTodayCompletedEventHandler(object sender, getTodayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTodayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTodayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bselectCompletedEventHandler(object sender, bselectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bselectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bselectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void uploadGrqmCompletedEventHandler(object sender, uploadGrqmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadGrqmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadGrqmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetxmlCompletedEventHandler(object sender, GetxmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetxmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetxmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void gettyPicCompletedEventHandler(object sender, gettyPicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gettyPicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gettyPicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPicCompletedEventHandler(object sender, getPicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StaticSelectCompletedEventHandler(object sender, StaticSelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StaticSelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StaticSelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void pselectCompletedEventHandler(object sender, pselectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pselectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pselectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTxmCompletedEventHandler(object sender, getTxmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTxmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTxmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void setApplicationContextCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getglbmCompletedEventHandler(object sender, getglbmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getglbmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getglbmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void uploadToServerCompletedEventHandler(object sender, uploadToServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadToServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uploadToServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMd5MCompletedEventHandler(object sender, getMd5MCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMd5MCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMd5MCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void downFromServerCompletedEventHandler(object sender, downFromServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class downFromServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal downFromServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591