//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathHISZGQJK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddl360g502:9000/Wcf.Ehr.Interface/clsWcfInterface.svc")]
        public string PathHISJK_Webstzxyy_clsWcfInterface {
            get {
                return ((string)(this["PathHISJK_Webstzxyy_clsWcfInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.110:9997/crds3/webservice/fujianforbcao.asmx")]
        public string PathHISJK_lzfbws_FuJianJieKouForBCao {
            get {
                return ((string)(this["PathHISJK_lzfbws_FuJianJieKouForBCao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.68:58080/csp/tongji/Tongji.COMM.SoapService.PathologySysService" +
            ".cls")]
        public string PathHISJK_whtjweb_PathologySysService {
            get {
                return ((string)(this["PathHISJK_whtjweb_PathologySysService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.82:8080/HealthWebservice.asmx")]
        public string PathHISJK_WebCAwhtj_HealthWebService {
            get {
                return ((string)(this["PathHISJK_WebCAwhtj_HealthWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://132.147.254.44:57772/csp/supcon/WebApp.WSGeneral.cls")]
        public string PathHISJK_WebXYCX_WSGeneral {
            get {
                return ((string)(this["PathHISJK_WebXYCX_WSGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://132.147.254.44:57772/csp/supcon/BS.WS.ExamFillerWS.cls")]
        public string PathHISJK_WebXYUP_ExamFillerWS {
            get {
                return ((string)(this["PathHISJK_WebXYUP_ExamFillerWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.58:9080/TJYYWebS/services/Upload_HtemrBaseInfo")]
        public string PathHISJK_whtjweb_sqd_Upload_HtemrBaseInfoService {
            get {
                return ((string)(this["PathHISJK_whtjweb_sqd_Upload_HtemrBaseInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.48.45.107/ktpis/PisServiceLJ.asmx")]
        public string PathHISJK_nbblrmyyWebReference_PisServiceLJ {
            get {
                return ((string)(this["PathHISJK_nbblrmyyWebReference_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.100.53:8080/Service.asmx")]
        public string PathHISJK_SZSZYY_Service {
            get {
                return ((string)(this["PathHISJK_SZSZYY_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.90.241/ZyhipWebService/WebServices/WSPacs.asmx")]
        public string PathHISJK_xmzyjcptWebservices_WSPacs {
            get {
                return ((string)(this["PathHISJK_xmzyjcptWebservices_WSPacs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.100.64:8082/PisServiceLJ.asmx")]
        public string PathHISJK_nbyzrmyyWeb_PisServiceLJ {
            get {
                return ((string)(this["PathHISJK_nbyzrmyyWeb_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.60.39:57772/csp/i-risservice/DHC.RIS.BS.WebRisService.cls")]
        public string PathHISJK_whxhyyWeb_WebRisService {
            get {
                return ((string)(this["PathHISJK_whxhyyWeb_WebRisService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.52.100:8081/PisServiceLJ.asmx")]
        public string PathHISJK_nbyzd2yyWEB_PisServiceLJ {
            get {
                return ((string)(this["PathHISJK_nbyzd2yyWEB_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.15:8080/Services/NYwclService")]
        public string PathHISJK_cszxyyWeb_NYwclService {
            get {
                return ((string)(this["PathHISJK_cszxyyWeb_NYwclService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.15:8080/Services/NYwclService")]
        public string PathHISZGQJK_cszxyyWeb_NYwclService {
            get {
                return ((string)(this["PathHISZGQJK_cszxyyWeb_NYwclService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.71.179.20:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PathHISZGQJK_xmzyjcptWebservices_WSPacs {
            get {
                return ((string)(this["PathHISZGQJK_xmzyjcptWebservices_WSPacs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.110:9997/crds3/webservice/fujianforbcao.asmx")]
        public string PathHISZGQJK_lzfbws_FuJianJieKouForBCao {
            get {
                return ((string)(this["PathHISZGQJK_lzfbws_FuJianJieKouForBCao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.48.45.107/ktpis/PisServiceLJ.asmx")]
        public string PathHISZGQJK_nbblrmyyWebReference_PisServiceLJ {
            get {
                return ((string)(this["PathHISZGQJK_nbblrmyyWebReference_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.52.100:8081/PisServiceLJ.asmx")]
        public string PathHISZGQJK_nbyzd2yyWEB_PisServiceLJ {
            get {
                return ((string)(this["PathHISZGQJK_nbyzd2yyWEB_PisServiceLJ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.0.100.53:8080/Service.asmx")]
        public string PathHISZGQJK_SZSZYY_Service {
            get {
                return ((string)(this["PathHISZGQJK_SZSZYY_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.82:8080/HealthWebservice.asmx")]
        public string PathHISZGQJK_WebCAwhtj_HealthWebService {
            get {
                return ((string)(this["PathHISZGQJK_WebCAwhtj_HealthWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddl360g502:9000/Wcf.Ehr.Interface/clsWcfInterface.svc")]
        public string PathHISZGQJK_Webstzxyy_clsWcfInterface {
            get {
                return ((string)(this["PathHISZGQJK_Webstzxyy_clsWcfInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://132.147.254.44:57772/csp/supcon/WebApp.WSGeneral.cls")]
        public string PathHISZGQJK_WebXYCX_WSGeneral {
            get {
                return ((string)(this["PathHISZGQJK_WebXYCX_WSGeneral"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://132.147.254.44:57772/csp/supcon/BS.WS.ExamFillerWS.cls")]
        public string PathHISZGQJK_WebXYUP_ExamFillerWS {
            get {
                return ((string)(this["PathHISZGQJK_WebXYUP_ExamFillerWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.68:58080/csp/tongji/Tongji.COMM.SoapService.PathologySysService" +
            ".cls")]
        public string PathHISZGQJK_whtjweb_PathologySysService {
            get {
                return ((string)(this["PathHISZGQJK_whtjweb_PathologySysService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.12.58:9080/TJYYWebS/services/Upload_HtemrBaseInfo")]
        public string PathHISZGQJK_whtjweb_sqd_Upload_HtemrBaseInfoService {
            get {
                return ((string)(this["PathHISZGQJK_whtjweb_sqd_Upload_HtemrBaseInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.60.39:57772/csp/i-risservice/DHC.RIS.BS.WebRisService.cls")]
        public string PathHISZGQJK_whxhyyWeb_WebRisService {
            get {
                return ((string)(this["PathHISZGQJK_whxhyyWeb_WebRisService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.80.166:8088/founderWebs/services/ICalculateService")]
        public string PathHISZGQJK_cdyyWeb_ICalculateService {
            get {
                return ((string)(this["PathHISZGQJK_cdyyWeb_ICalculateService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.141.9/KCIS/CISService.asmx")]
        public string PathHISZGQJK_wys_pacs_web_CISService {
            get {
                return ((string)(this["PathHISZGQJK_wys_pacs_web_CISService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.0.1.146:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PathHISZGQJK_xm1yWeb_WSInterface {
            get {
                return ((string)(this["PathHISZGQJK_xm1yWeb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://svrdebug.test.com/CoreService/EventBus.svc")]
        public string PathHISZGQJK_gdsrmyyWeb_EventBusSvc {
            get {
                return ((string)(this["PathHISZGQJK_gdsrmyyWeb_EventBusSvc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://168.192.8.10:8080/WebService/services/MatrixService")]
        public string PathHISZGQJK_SXYDDEYYWeb_MatrixService {
            get {
                return ((string)(this["PathHISZGQJK_SXYDDEYYWeb_MatrixService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://198.100.100.8:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PathHISZGQJK_fjsfybjyWeb_WSInterface {
            get {
                return ((string)(this["PathHISZGQJK_fjsfybjyWeb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.1.1.71:1508/services/WSInterface_cdr.WSInterface_cdrHttpSoap11Endpoint")]
        public string PathHISZGQJK_fjsfybjyWebCX_WSInterface {
            get {
                return ((string)(this["PathHISZGQJK_fjsfybjyWebCX_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.158:1405/services/FGPLService.FGPLServiceHttpSoap12Endpoint")]
        public string PathHISZGQJK_shsjdqzyyyweb_FGPLService {
            get {
                return ((string)(this["PathHISZGQJK_shsjdqzyyyweb_FGPLService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.0.19.148:1506/services/WSInterface.WSInterfaceHttpSoap11Endpoint")]
        public string PathHISZGQJK_xmyyweb_SendMessage {
            get {
                return ((string)(this["PathHISZGQJK_xmyyweb_SendMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        public string PathHISZGQJK_sh7yWeb_webserviceService {
            get {
                return ((string)(this["PathHISZGQJK_sh7yWeb_webserviceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.19:8080/Services/NYwclService")]
        public string PathHISZGQJK_cszxyyweb2_NYwclService {
            get {
                return ((string)(this["PathHISZGQJK_cszxyyweb2_NYwclService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://223.220.200.45:1506/services/WSInterface.WSInterfaceHttpSoap12Endpoint")]
        public string PathHISZGQJK_ayd2fyweb_WSInterface {
            get {
                return ((string)(this["PathHISZGQJK_ayd2fyweb_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://100.100.42.107/GetEHMQ/EHSBMQService.asmx")]
        public string PathHISZGQJK_EHSBMQWeb_Service {
            get {
                return ((string)(this["PathHISZGQJK_EHSBMQWeb_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://120.197.142.53:9180/hdepc/services/hisWebService")]
        public string PathHISZGQJK_gddhyyweb_WSServiceService {
            get {
                return ((string)(this["PathHISZGQJK_gddhyyweb_WSServiceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2089/ZSZL_MQService2010/MQService.asmx")]
        public string PathHISZGQJK_ZszlWeb_ZGQ_Service {
            get {
                return ((string)(this["PathHISZGQJK_ZszlWeb_ZGQ_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:3654/cdrmyyWebService/IBMMQService.asmx")]
        public string PathHISZGQJK_cdrmyymq_Service {
            get {
                return ((string)(this["PathHISZGQJK_cdrmyymq_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.9.199.12:8003/HisForInspectItemService.asmx")]
        public string PathHISZGQJK_gdszyyMzHisWeb_HisForInspectItemService {
            get {
                return ((string)(this["PathHISZGQJK_gdszyyMzHisWeb_HisForInspectItemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5199/BL2MQWebService/FZMQService.asmx")]
        public string PathHISZGQJK_BL2FZMQWeb_Service {
            get {
                return ((string)(this["PathHISZGQJK_BL2FZMQWeb_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.200.119:57772/csp/xyepacs/PACS.BS.Service.cls")]
        public string PathHISZGQJK_xy2yweb_XYEPACS {
            get {
                return ((string)(this["PathHISZGQJK_xy2yweb_XYEPACS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.2.116:57772/csp/dhcens/DHC.Pis.XiangYaOne.BS.Web.cls")]
        public string PathHISZGQJK_xyfyWeb1_DHC_Pis_XiangYaOne {
            get {
                return ((string)(this["PathHISZGQJK_xyfyWeb1_DHC_Pis_XiangYaOne"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.168.35.249/BLToMQWebSrv/FZMQService.asmx")]
        public string PathHISZGQJK_BLToFZMQWS_Service {
            get {
                return ((string)(this["PathHISZGQJK_BLToFZMQWS_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.3.174/csp/jhip/JHIP.PACS.BS.PacsWS.cls")]
        public string PathHISZGQJK_gds2websvr_PacsWS {
            get {
                return ((string)(this["PathHISZGQJK_gds2websvr_PacsWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.101.2.170:9008/MZWebService.asmx")]
        public string PathHISZGQJK_sdwhslyyWeb_MZWebService {
            get {
                return ((string)(this["PathHISZGQJK_sdwhslyyWeb_MZWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.20.128.62:1506/services/WSInterface.WSInterfaceHttpSoap11Endpoint")]
        public string PathHISZGQJK_XJZLYYWEB_WSInterface {
            get {
                return ((string)(this["PathHISZGQJK_XJZLYYWEB_WSInterface"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.16.95.189:8081/PDAService.asmx")]
        public string PathHISZGQJK_GzzszlyyFzLis_PDAService {
            get {
                return ((string)(this["PathHISZGQJK_GzzszlyyFzLis_PDAService"]));
            }
        }
    }
}
