//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace LGHISJKZGQ.BLWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PisServiceLJSoap", Namespace="http://tempuri.org/")]
    public partial class PisServiceLJ : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PatBillWritePISOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetPISReportInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PisServiceLJ() {
            this.Url = global::LGHISJKZGQ.Properties.Settings.Default.PATHGETHISZGQ_WebReference_PisServiceLJ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PatBillWritePISCompletedEventHandler PatBillWritePISCompleted;
        
        /// <remarks/>
        public event SetPISReportInfoCompletedEventHandler SetPISReportInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PatBillWritePIS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PatBillWritePIS(string sHISKeyNo, ref string sBillInfo, ref string sSampleInfo, int type) {
            object[] results = this.Invoke("PatBillWritePIS", new object[] {
                        sHISKeyNo,
                        sBillInfo,
                        sSampleInfo,
                        type});
            sBillInfo = ((string)(results[1]));
            sSampleInfo = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PatBillWritePISAsync(string sHISKeyNo, string sBillInfo, string sSampleInfo, int type) {
            this.PatBillWritePISAsync(sHISKeyNo, sBillInfo, sSampleInfo, type, null);
        }
        
        /// <remarks/>
        public void PatBillWritePISAsync(string sHISKeyNo, string sBillInfo, string sSampleInfo, int type, object userState) {
            if ((this.PatBillWritePISOperationCompleted == null)) {
                this.PatBillWritePISOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPatBillWritePISOperationCompleted);
            }
            this.InvokeAsync("PatBillWritePIS", new object[] {
                        sHISKeyNo,
                        sBillInfo,
                        sSampleInfo,
                        type}, this.PatBillWritePISOperationCompleted, userState);
        }
        
        private void OnPatBillWritePISOperationCompleted(object arg) {
            if ((this.PatBillWritePISCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PatBillWritePISCompleted(this, new PatBillWritePISCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetPISReportInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetPISReportInfo(decimal sqdbh, string reportInfo) {
            object[] results = this.Invoke("SetPISReportInfo", new object[] {
                        sqdbh,
                        reportInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetPISReportInfoAsync(decimal sqdbh, string reportInfo) {
            this.SetPISReportInfoAsync(sqdbh, reportInfo, null);
        }
        
        /// <remarks/>
        public void SetPISReportInfoAsync(decimal sqdbh, string reportInfo, object userState) {
            if ((this.SetPISReportInfoOperationCompleted == null)) {
                this.SetPISReportInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetPISReportInfoOperationCompleted);
            }
            this.InvokeAsync("SetPISReportInfo", new object[] {
                        sqdbh,
                        reportInfo}, this.SetPISReportInfoOperationCompleted, userState);
        }
        
        private void OnSetPISReportInfoOperationCompleted(object arg) {
            if ((this.SetPISReportInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetPISReportInfoCompleted(this, new SetPISReportInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PatBillWritePISCompletedEventHandler(object sender, PatBillWritePISCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PatBillWritePISCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PatBillWritePISCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sBillInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string sSampleInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetPISReportInfoCompletedEventHandler(object sender, SetPISReportInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetPISReportInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetPISReportInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591