//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace PathHISZGQJK.sh7yWeb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExamResultInputSoapBinding", Namespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
    public partial class webserviceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback isAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryBaseSnOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public webserviceService() {
            this.Url = global::PathHISZGQJK.Properties.Settings.Default.PathHISZGQJK_sh7yWeb_webserviceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getNameCompletedEventHandler getNameCompleted;
        
        /// <remarks/>
        public event isAliveCompletedEventHandler isAliveCompleted;
        
        /// <remarks/>
        public event queryBaseSnCompletedEventHandler queryBaseSnCompleted;
        
        /// <remarks/>
        public event validateItemCompletedEventHandler validateItemCompleted;
        
        /// <remarks/>
        public event updateItemCompletedEventHandler updateItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://exam.rich.com", ResponseNamespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        [return: System.Xml.Serialization.SoapElementAttribute("getNameReturn")]
        public string getName() {
            object[] results = this.Invoke("getName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getNameAsync() {
            this.getNameAsync(null);
        }
        
        /// <remarks/>
        public void getNameAsync(object userState) {
            if ((this.getNameOperationCompleted == null)) {
                this.getNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNameOperationCompleted);
            }
            this.InvokeAsync("getName", new object[0], this.getNameOperationCompleted, userState);
        }
        
        private void OngetNameOperationCompleted(object arg) {
            if ((this.getNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNameCompleted(this, new getNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://exam.rich.com", ResponseNamespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        [return: System.Xml.Serialization.SoapElementAttribute("isAliveReturn")]
        public string isAlive() {
            object[] results = this.Invoke("isAlive", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void isAliveAsync() {
            this.isAliveAsync(null);
        }
        
        /// <remarks/>
        public void isAliveAsync(object userState) {
            if ((this.isAliveOperationCompleted == null)) {
                this.isAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisAliveOperationCompleted);
            }
            this.InvokeAsync("isAlive", new object[0], this.isAliveOperationCompleted, userState);
        }
        
        private void OnisAliveOperationCompleted(object arg) {
            if ((this.isAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isAliveCompleted(this, new isAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://exam.rich.com", ResponseNamespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        [return: System.Xml.Serialization.SoapElementAttribute("queryBaseSnReturn")]
        public string queryBaseSn(string name1) {
            object[] results = this.Invoke("queryBaseSn", new object[] {
                        name1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryBaseSnAsync(string name1) {
            this.queryBaseSnAsync(name1, null);
        }
        
        /// <remarks/>
        public void queryBaseSnAsync(string name1, object userState) {
            if ((this.queryBaseSnOperationCompleted == null)) {
                this.queryBaseSnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBaseSnOperationCompleted);
            }
            this.InvokeAsync("queryBaseSn", new object[] {
                        name1}, this.queryBaseSnOperationCompleted, userState);
        }
        
        private void OnqueryBaseSnOperationCompleted(object arg) {
            if ((this.queryBaseSnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBaseSnCompleted(this, new queryBaseSnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://exam.rich.com", ResponseNamespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        [return: System.Xml.Serialization.SoapElementAttribute("validateItemReturn")]
        public string validateItem(string jsonstr, string jyzx) {
            object[] results = this.Invoke("validateItem", new object[] {
                        jsonstr,
                        jyzx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validateItemAsync(string jsonstr, string jyzx) {
            this.validateItemAsync(jsonstr, jyzx, null);
        }
        
        /// <remarks/>
        public void validateItemAsync(string jsonstr, string jyzx, object userState) {
            if ((this.validateItemOperationCompleted == null)) {
                this.validateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateItemOperationCompleted);
            }
            this.InvokeAsync("validateItem", new object[] {
                        jsonstr,
                        jyzx}, this.validateItemOperationCompleted, userState);
        }
        
        private void OnvalidateItemOperationCompleted(object arg) {
            if ((this.validateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateItemCompleted(this, new validateItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://exam.rich.com", ResponseNamespace="http://155.165.13.14:8085/ExamResultService/services/ExamResultInput")]
        [return: System.Xml.Serialization.SoapElementAttribute("updateItemReturn")]
        public string updateItem(string jsonstr, string jyzx) {
            object[] results = this.Invoke("updateItem", new object[] {
                        jsonstr,
                        jyzx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateItemAsync(string jsonstr, string jyzx) {
            this.updateItemAsync(jsonstr, jyzx, null);
        }
        
        /// <remarks/>
        public void updateItemAsync(string jsonstr, string jyzx, object userState) {
            if ((this.updateItemOperationCompleted == null)) {
                this.updateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateItemOperationCompleted);
            }
            this.InvokeAsync("updateItem", new object[] {
                        jsonstr,
                        jyzx}, this.updateItemOperationCompleted, userState);
        }
        
        private void OnupdateItemOperationCompleted(object arg) {
            if ((this.updateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateItemCompleted(this, new updateItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getNameCompletedEventHandler(object sender, getNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void isAliveCompletedEventHandler(object sender, isAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void queryBaseSnCompletedEventHandler(object sender, queryBaseSnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBaseSnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBaseSnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void validateItemCompletedEventHandler(object sender, validateItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void updateItemCompletedEventHandler(object sender, updateItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591